시작하기전에 읽어들일 파일 모두 업로드 하고 시작하기

In [1]:
import pandas as pd

df = pd.read_csv("student_info.csv")
df

    이름      학과  학년 성별
0  김지은  컴퓨터과학과   1  여
1  박은화   국어교육과   2  여
2  박길준   토목공학과   3  남
3  이미도    간호학과   4  여
4  이진영    물리학과   4  남

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/student_info.csv")
df

    이름      학과  학년 성별
0  김지은  컴퓨터과학과   1  여
1  박은화   국어교육과   2  여
2  박길준   토목공학과   3  남
3  이미도    간호학과   4  여
4  이진영    물리학과   4  남

In [2]:
# Excel file open 시트가 한개인경우
stu_df =  pd.read_excel('stu_info_s1.xlsx')
stu_df

    이름      학과  학년 성별
0  김지은  컴퓨터과학과   1  여
1  박은화   국어교육과   2  여
2  박길준   토목공학과   3  남
3  이미도    간호학과   4  여
4  이진영    물리학과   4  남

In [ ]:
stu_df =  pd.read_excel('stu_info_s1.xlsx', header=None)
print(stu_df)

     0       1   2   3
0  이름       학과  학년  성별
1  김지은  컴퓨터과학과   1   여
2  박은화   국어교육과   2   여
3  박길준   토목공학과   3   남
4  이미도    간호학과   4   여
5  이진영    물리학과   4   남

In [ ]:
#시트가 여러개인경우
df1 = pd.read_excel('stu_info_s2.xlsx', "Sheet1")
df2 = pd.read_excel('stu_info_s2.xlsx', "Sheet2")

print(df1)
print('\n')
print(df2)

In [ ]:
with pd.ExcelFile('stu_info_s2.xlsx') as xls:
    df1 = pd.read_excel(xls, "Sheet1")
    df2 = pd.read_excel(xls, "Sheet2")

print(df1)
print('\n')
print(df2)

    이름      학과  학년 성별
0  김지은  컴퓨터과학과   1  여
1  박은화   국어교육과   2  여
2  박길준   토목공학과   3  남
3  이미도    간호학과   4  여
4  이진영    물리학과   4  남


    이름     학과  학년 성별
0  강호준  화학공학과   3  남
1  김정수  국어교육과   2  남
2  강선아  화학공학과   1  여
3  오수진   간호학과   1  여
4  정진아   간호학과   1  여

In [ ]:
xlsx = pd.ExcelFile('stu_info_s2.xlsx')
df = xlsx
print(xlsx)

<pandas.io.excel._base.ExcelFile object at 0x7f1434ad1610>

In [ ]:
'''
xlsx = pd.ExcelFile("path_to_file.xls")
df = pd.read_excel(xlsx, "Sheet1")


with pd.ExcelFile("path_to_file.xls") as xls:
    df1 = pd.read_excel(xls, "Sheet1")
    df2 = pd.read_excel(xls, "Sheet2")

data = {}
# For when Sheet1's format differs from Sheet2
with pd.ExcelFile("path_to_file.xls") as xls:
    data["Sheet1"] = pd.read_excel(xls, "Sheet1", index_col=None, na_values=["NA"])
    data["Sheet2"] = pd.read_excel(xls, "Sheet2", index_col=1)

data = {}
with pd.ExcelFile("path_to_file.xls") as xls:
    data["Sheet1"] = pd.read_excel(xls, "Sheet1", index_col=None, na_values=["NA"])
    data["Sheet2"] = pd.read_excel(xls, "Sheet2", index_col=None, na_values=["NA"])

# equivalent using the read_excel function
data = pd.read_excel(
    "path_to_file.xls", ["Sheet1", "Sheet2"], index_col=None, na_values=["NA"]
)
'''

In [ ]:
import pandas as pd
stu_df3 =  pd.read_json('stu_info.json')
print(stu_df3 )

    이름      학과  학년 성별
0  김지은  컴퓨터과학과   1  여
1  박은화   국어교육과   2  여
2  박길준   토목공학과   3  남
3  이미도    간호학과   4  여
4  이진영    물리학과   4  남

In [ ]:
#CSV 파일로 저장하기
print(df1)
print('\n')
print(df2)
print('\n')

df_to_concat = pd.concat([df1, df2], ignore_index=True)
print(df_to_concat)

df_to_concat.to_csv("df_to_csv.csv")

    이름      학과  학년 성별
0  김지은  컴퓨터과학과   1  여
1  박은화   국어교육과   2  여
2  박길준   토목공학과   3  남
3  이미도    간호학과   4  여
4  이진영    물리학과   4  남


    이름     학과  학년 성별
0  강호준  화학공학과   3  남
1  김정수  국어교육과   2  남
2  강선아  화학공학과   1  여
3  오수진   간호학과   1  여
4  정진아   간호학과   1  여


    이름      학과  학년 성별
0  김지은  컴퓨터과학과   1  여
1  박은화   국어교육과   2  여
2  박길준   토목공학과   3  남
3  이미도    간호학과   4  여
4  이진영    물리학과   4  남
5  강호준   화학공학과   3  남
6  김정수   국어교육과   2  남
7  강선아   화학공학과   1  여
8  오수진    간호학과   1  여
9  정진아    간호학과   1  여

In [ ]:
#excel 파일로 저장하기
print(df1)
print('\n')
print(df2)
print('\n')

df_to_concat = pd.concat([df1, df2], ignore_index=True)  #하나의 파일로 합쳐서 저장
df_to_concat.to_excel("df_to_excel.xlsx")

writer = pd.ExcelWriter("df_to_excelwriter.xlsx")
df1.to_excel(writer, sheet_name="sheet1")
df2.to_excel(writer, sheet_name="sheet2")
writer.save()

    이름      학과  학년 성별
0  김지은  컴퓨터과학과   1  여
1  박은화   국어교육과   2  여
2  박길준   토목공학과   3  남
3  이미도    간호학과   4  여
4  이진영    물리학과   4  남


    이름     학과  학년 성별
0  강호준  화학공학과   3  남
1  김정수  국어교육과   2  남
2  강선아  화학공학과   1  여
3  오수진   간호학과   1  여
4  정진아   간호학과   1  여

In [ ]:
#json 파일로 저장하기
print(df1)

df1.to_json("df_to_json.json")

    이름      학과  학년 성별
0  김지은  컴퓨터과학과   1  여
1  박은화   국어교육과   2  여
2  박길준   토목공학과   3  남
3  이미도    간호학과   4  여
4  이진영    물리학과   4  남